### LOCAL TEST

### Test locally App Hello World
GET http://localhost:3000/

### Test locally get all contacts
GET http://localhost:3000/contacts

### Test locally get contact by id
GET http://localhost:3000/contacts/662b2df0e5d4f9d90f0c9695


### Create contact
POST http://localhost:3000/contacts 
content-type: application/json

{
    "firstName": "Andres",
    "lastName": "Costanzillo",
    "email": "acaca@example.com",
    "favoriteColor": "White",
    "birthday": "1991-05-15"
  }

### Update contact
PUT http://localhost:3000/contacts/66331ed5967ae928c75397ca 
content-type: application/json

{
    "firstName": "Daniel",
    "lastName": "Hofmann",
    "email": "eldano@example.com",
    "favoriteColor": "Blur",
    "birthday": "1995-03-22"
  }

### Delete contact
DELETE http://localhost:3000/contacts/66331ed5967ae928c75397ca





### PRODUCTION

### Test App Hello World
GET https://cse-341-project1-kvlw.onrender.com/

### Test get all contacts
GET https://cse-341-project1-kvlw.onrender.com/contacts

### Test get contact by id
GET https://cse-341-project1-kvlw.onrender.com/contacts/662b2df0e5d4f9d90f0c9695


### Create contact
POST https://cse-341-project1-kvlw.onrender.com/contacts 
content-type: application/json

{
    "firstName": "Andres",
    "lastName": "Costanzillo",
    "email": "acaca@example.com",
    "favoriteColor": "White",
    "birthday": "1991-05-15"
  }

### Update contact
PUT https://cse-341-project1-kvlw.onrender.com/contacts/66331ed5967ae928c75397ca 
content-type: application/json

{
    "firstName": "Daniel",
    "lastName": "Hofmann",
    "email": "eldano@example.com",
    "favoriteColor": "Blur",
    "birthday": "1995-03-22"
  }

### Delete contact
DELETE https://cse-341-project1-kvlw.onrender.com/contacts/66331ed5967ae928c75397ca
